---
title: "Plotting Roots"
author: "Dalmolin Systems Biology Group"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  results = FALSE
)
```

## Import libraries

```{r libs}
library(RedeR)
library(dplyr)
library(igraph)
library(ggplot2)
library(ggraph)
library(ggforce)
library(tidyr)
library(scales)
library(ggtext)
```

## Load Data

```{r}
load("../results/plots/graph")
metastasis_genes <- vroom::vroom("../_dev/gene_publication.csv", delim = ",")
nodelist <- vroom::vroom("../results/orthology_data/nodelist.csv")
```

```{r}
list_intersect <- as.data.frame(intersect(nodelist$preferredName, metastasis_genes$gene))
colnames(list_intersect) <- "gene"


nodelist_filtered <- nodelist %>%
  mutate(node_color = case_when(
    clade_name == "Metamonada" ~ "#4CA375",
    clade_name == "Choanoflagellata" ~ "#D17878",
    clade_name == "Actinopterygii" ~ "#4A85C2"
    TRUE ~ "#999999FF"
  )) %>%
  mutate(node_size = case_when(
    clade_name %in% c("Metamonada","Choanoflagellata","Actinopterygii") ~ 50,
    TRUE ~ 35
  )) %>% 
  mutate(node_linecolor = case_when(
    preferredName %in% metastasis_genes$gene ~ "#6A0DAD", 
    TRUE ~ "#999999FF"
  )) %>%
    mutate(node_linewidth = case_when(
    preferredName %in% metastasis_genes$gene ~ 3, 
    TRUE ~ 1
    )) %>%
  filter(root >= 20)

list_intersect |> 
  vroom::vroom_write(file = "../_dev/metastasis_intersect.csv", delim = ",")
```

## Create Subgraphs

```{r}
# Actinopterygii subgraph
g3 <- subg(g = graph, dat = nodelist_filtered[nodelist_filtered$root %in% 20:37, ], refcol = 1, connected = F, maincomp = F, transdat = T) %>%
      att.setv(from="queryItem", to="nodeLabel")

V(g3)$nodeColor      <- V(g3)$node_color
V(g3)$nodeSize       <- V(g3)$node_size
V(g3)$nodeLineColor  <- V(g3)$node_linecolor
V(g3)$nodeLineWidth  <- V(g3)$node_linewidth

# Choanoflagellata subgraph
g2 <- subg(g = graph, dat = nodelist_filtered[nodelist_filtered$root %in% 30:37, ], refcol = 1, connected = F, maincomp = F, transdat = T) %>% 
      att.setv(from="queryItem", to="nodeLabel")

V(g2)$nodeColor      <- V(g2)$node_color
V(g2)$nodeSize       <- V(g2)$node_size
V(g2)$nodeLineColor  <- V(g2)$node_linecolor
V(g2)$nodeLineWidth  <- V(g2)$node_linewidth

# Metamonada subgraph
g1 <- subg(g = graph, dat = nodelist_filtered[nodelist_filtered$root %in% 37, ], refcol = 1, connected = F, maincomp = F, transdat = T) %>% 
      att.setv(from="queryItem", to="nodeLabel")

V(g1)$nodeColor      <- V(g1)$node_color
V(g1)$nodeSize       <- V(g1)$node_size
V(g1)$nodeLineColor  <- V(g1)$node_linecolor
V(g1)$nodeLineWidth  <- V(g1)$node_linewidth
```

## Start RedeR

```{r}
startRedeR()
```

## Create Nested Graph

```{r}
N3 <- addGraphToRedeR( g3, gcoord=c(0,0), gscale=80, isNested=FALSE, theme='tm1', zoom=30)
N3 <- nestNodes(nodes = V(g3)$name, parent = N3, theme = 'tm1', gatt = list(nestLabel = "Human-Actinopterygii",
                                                                            nestShape = "Circle",
                                                                            nestSize = 3000,
                                                                            nestLabelSize = 80,
                                                                            nestLabelColor = "#4A85C2",
                                                                            nestLabelCoords = c(x=-10, y=-2000),
                                                                            nestLineType = "SOLID",
                                                                            nestLineWidth = 15,
                                                                            nestLineColor = "#4A85C2"))
  
N5 <- nestNodes(nodes=V(g2)$name, gcoord = c(40, 57), parent=N3, theme='tm1', gatt = list(nestLabel = "Human-Choanoflagellata",
                                                                       nestShape = "Circle",
                                                                       nestSize = 2300,
                                                                       nestLabelSize = 80,
                                                                       nestLabelColor = "#D17878",
                                                                       nestLabelCoords = c(x=-9, y=-1780),
                                                                       nestLineType = "SOLID",
                                                                       nestLineWidth = 15,
                                                                       nestLineColor = "#D17878"))


nestNodes( nodes=V(g1)$name, gcoord = c(41, 62), parent=N5, theme='tm1', gatt = list(nestLabel = "Human-Metamonada",
                                                               nestShape = "Circle",
                                                               nestSize = 1600,
                                                               nestLabelSize = 80,
                                                               nestLabelColor = "#4CA375",
                                                               nestLabelCoords = c(x=-7, y=-1500),
                                                               nestLineType = "SOLID",
                                                               nestLineWidth = 15,
                                                               nestLineColor = "#4CA375"))

mergeOutEdges( nlevels=2)

# RedeR force-directed parameters
 relaxRedeR(
p1 = 200,
p2 = 500,
p3 = 200,
p4 = 350,
p5 = 50,
p6 = 75,
p7 = 100,
p8 = 300,
p9 = 1500
)
```

## Get RedeR Graph

```{r}
graph_RedeR <- getGraphFromRedeR(type = "node")
V(graph_RedeR)$name <- gsub("\\..*", "", V(graph_RedeR)$name)

# Setting graph2 attributes
graph_ggplot <- graph_RedeR

index_match <- match(V(graph_RedeR)$nodeLabel, V(g3)$nodeLabel)

 V(graph_ggplot)$cog_id        <- V(g3)$cog_id[index_match]
 V(graph_ggplot)$root          <- V(g3)$root[index_match]
 V(graph_ggplot)$clade         <- V(g3)$clade_name[index_match]
 V(graph_ggplot)$queryItem     <- V(g3)$queryItem[index_match]
 V(graph_ggplot)$taxonId       <- V(g3)$ncbiTaxonId[index_match]
 V(graph_ggplot)$taxonName     <- V(g3)$taxonName[index_match]
 V(graph_ggplot)$preferredName <- V(g3)$preferredName[index_match]
 V(graph_ggplot)$annotation    <- V(g3)$annotation[index_match]

 V(graph_ggplot)$`cellular extravasation`                  <- V(g3)$`cellular extravasation`[index_match]
 V(graph_ggplot)$`cell junction organization`              <- V(g3)$`cell junction organization`[index_match]
 V(graph_ggplot)$`cell adhesion`                           <- V(g3)$`cell adhesion`[index_match]
 V(graph_ggplot)$`extracellular matrix organization`       <- V(g3)$`extracellular matrix organization`[index_match]
 V(graph_ggplot)$`epithelial to mesenchymal transition`    <- V(g3)$`epithelial to mesenchymal transition`[index_match]
 V(graph_ggplot)$`regulation of metallopeptidase activity` <- V(g3)$`regulation of metallopeptidase activity`[index_match]

save(graph_ggplot, file = "../results/plots/graph_ggplot")
 
 # Setting graph1 attributes
index_match <- match( V(g3)$nodeLabel,V(graph_RedeR)$nodeLabel) 
 
V(g3)$x <- V(graph_RedeR)$x[index_match]
V(g3)$y <- V(graph_RedeR)$y[index_match]

#graph_RedeR <- g3

save(graph_RedeR, file = "../results/plots/graph_RedeR")
```

# Plot Nested Network

```{r}
load("../results/plots/graph_ggplot")

circles <- data.frame(
  x = c(35, 43, 50),
  y = c(29, 38.7, 48.5),
  r = c(27.5, 39.5, 52),
  color = c("#4CA375", "#D17878", "#4A85C2")
)

ggraph::ggraph(graph_ggplot,
               "manual",
               x = V(graph_ggplot)$x,
               y = V(graph_ggplot)$y) +
  ggraph:: geom_edge_link0(edge_width = 0.8, color = "#90909020") +
  geom_node_point(aes(color = I(nodeColor)), size = V(graph_ggplot)$nodeSize/12) +
  geom_node_text(aes(label = V(graph_ggplot)$queryItem), 
                 colour = "red", nudge_x = 0.8, nudge_y = 0.8, size = 2) +
  geom_circle(data = circles, aes(x0 = x, y0 = y, r = r, color = I(color))) + 
  theme_void() +
  coord_fixed()
```

```{r}
process_colors <- c(
  "cell adhesion"                              = "#06141FFF",
  "extracellular matrix organization"          = "#742C14FF",
  "epithelial to mesenchymal transition"       = "#3D4F7DFF",
  "cell junction organization"                 = "#72874EFF",
  "regulation of metallopeptidase activity"    = "#E48C2AFF",
  "cellular extravasation"                     = "#046E8FFF"
)

for (process in names(process_colors)) {
  
V(graph_ggplot)$tempColor <- ifelse(V(graph_ggplot)$nodeSize == 35, "lightgray", 
                               ifelse(vertex_attr(graph_ggplot, process) == 1, 
                                      process_colors[process], "darkgray"))


p <- ggraph(graph_ggplot, "manual", x = V(graph_ggplot)$x, y = V(graph_ggplot)$y) +
    geom_edge_link0(edge_width = 0.8, color = "#90909020") +
    geom_node_point(aes(color = I(tempColor)), size = V(graph_ggplot)$nodeSize / 12) +
    geom_node_text(aes(label = V(graph_ggplot)$queryItem), 
                   colour = "red", nudge_x = 0.8, nudge_y = 0.8, size = 2) +
    geom_circle(data = circles, aes(x0 = x, y0 = y, color = I(color), r = r)) + 
    ggtitle(paste("Biological Process:", process)) +
    theme_void() +
    coord_fixed()
    

print(p)
}
```

# Distribution

# Defining Functions

```{r}
BP_by_clade <- function(data) {
  data %>%
    pivot_longer(
      cols = c(`cellular extravasation`, `cell junction organization`, 
               `cell adhesion`, `extracellular matrix organization`, 
               `epithelial to mesenchymal transition`, 
               `regulation of metallopeptidase activity`),
      names_to = "process",
      values_to = "presence"
    ) %>%
    filter(presence == 1) %>%
    group_by(clade_name, process, root) %>% 
    summarise(count = n(), .groups = "drop") %>%
    mutate(total_genes = sum(count), .by = process) %>%
    mutate(proportion = count / total_genes)
}

plot_stacked_bar_chart <- function(data) {
   # Definir os grupos de interesse
   clados_interesse <- c("Metamonada", "Choanoflagellata", "Actinopterygii")
   
   # Criar as categorias "Outros" com base nos intervalos de root
   filtered_data <- data %>%
     mutate(clade_group = case_when(
       clade_name == "Metamonada" ~ "Metamonada",
       root >= 31 & root <= 36 ~ "Intermediate M-C",
       clade_name == "Choanoflagellata" ~ "Choanoflagellata",
       root >= 21 & root <= 29 ~ "Intermediate C-A",
       clade_name == "Actinopterygii" ~ "Actinopterygii",
       TRUE ~ NA_character_
     )) %>%
     filter(!is.na(clade_group)) %>%
     mutate(clade_group = factor(clade_group, 
                                 levels = c("Metamonada", "Intermediate M-C", 
                                            "Choanoflagellata", "Intermediate C-A", 
                                            "Actinopterygii")))
   
   # Ajustar a largura das barras: mais finas para "Outros"
   filtered_data <- filtered_data %>%
     mutate(bar_width = ifelse(grepl("Intermediate", clade_group), 0.4, 0.8)) %>%
     mutate(alpha = ifelse(grepl("Intermediate", clade_group), 0.55, 1))
   
   # Criar o gráfico de barras empilhadas com larguras ajustadas
   ggplot(filtered_data, aes(x = clade_group, y = proportion, fill = process, 
                             width = bar_width)) +
     geom_bar(position = "fill", stat = "identity", color = NA, alpha = filtered_data$alpha) +
     theme_minimal() +
     labs(
       title = "Biological Process Distribution",
       x="",
       y = "Genes Proportion",
       fill = "Biological Processes"
     ) +
     scale_fill_manual(values = c(
       "cell adhesion"                               = "#06141FFF"
       ,"extracellular matrix organization"          = "#742C14FF"
       ,"epithelial to mesenchymal transition"       = "#3D4F7DFF"
       ,"regulation of metallopeptidase activity"    = "#E48C2AFF"
       ,"cell junction organization"                  ="#72874EFF"
       ,"cellular extravasation"                      ="#046E8FFF"
     )) + 
     scale_y_continuous(labels = scales::percent) +
     theme(
       axis.text = element_text(size = 12),
       axis.title = element_text(size = 14),
       axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
       legend.position = "right",
       plot.title = element_text(size = 16, hjust = 0.5, face = "bold"),
       panel.grid = element_blank()
     ) +
     guides(alpha = "none")
 }
```

```{r}
df_proportion <- BP_by_clade(nodelist_filtered)
```

```{r}
plot_stacked_bar_chart(df_proportion)
```

## Hipergeometric Test

```{r}
nodelist <- vroom::vroom("../results/orthology_data/nodelist.csv")

   clades <- unique(nodelist$clade_name)
   processes <- c("cell adhesion", "extracellular matrix organization", 
                  "epithelial to mesenchymal transition", "regulation of metallopeptidase activity", 
                  "cell junction organization", "cellular extravasation")
   
  
   result <- list()
   
   for (process in processes) {
     for (clade in clades) {
       
       N <- length(nodelist$queryItem)  
       M <- sum(nodelist[[process]])  
       n <- length(which(nodelist$clade_name == clade))  
       k <- sum(filter(nodelist, clade_name == clade)[[process]])  
       
       p_valor <- 1 - phyper(k - 1, M, N - M, n)
       
       result[[paste(process, clade, sep = "_")]] <- c(process, clade, k, M, N, n, p_valor)
     }
   }
   
   hipergeometric_df <- do.call(rbind, result) %>%
     as.data.frame() %>%
     setNames(c("Process", "clade_name", "k", "M", "N", "n", "p.val")) %>% 
     arrange(p.val)
     rownames(hipergeometric_df) <- NULL
   
   head(hipergeometric_df)
```

```{r}
hipergeometric_df$p.val <- as.numeric(hipergeometric_df$p.val)
hipergeometric_df$p.val_color <- ifelse(hipergeometric_df$p.val > 0.05, "gray", "red")

i <- nodelist %>% 
  select(clade_name, root) %>% 
  unique()

hipergeometric_df <- hipergeometric_df %>%
  inner_join(i, by = "clade_name")

hipergeometric_df$clade_name <- factor(hipergeometric_df$clade_name, 
    levels = unique(hipergeometric_df$clade_name[order(hipergeometric_df$root)]))


hipergeometric_df$Process <- factor(hipergeometric_df$Process, 
                                    levels = c("extracellular matrix organization", 
                                               "epithelial to mesenchymal transition", 
                                               "cell junction organization",
                                               "regulation of metallopeptidase activity",
                                               "cell adhesion", 
                                               "cellular extravasation"))

ggplot(hipergeometric_df, aes(x = Process, 
                              y = clade_name, 
                              size = as.numeric(n), 
                              color = p.val_color)) +
  geom_point() +
  scale_color_manual(values = c("gray" = "gray", "red" = "red"), 
                     labels = c("Not Significant", "Significant")) +  
  labs(x = "Biological Process", y = "Clade", size = "Number of Genes", color = "Significance") +
  scale_size_continuous(breaks = c(10, 50, 98), labels = c("10 genes", "50 genes", "100 genes")) + 
  theme_minimal() +
  ggtitle("Hipergeometric Test") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank()) +
  scale_y_discrete(labels = function(x) {
    x <- gsub("Metamonada", "<b>Metamonada</b>", x)
    x <- gsub("Actinopterygii", "<b>Actinopterygii</b>", x)
    x <- gsub("Choanoflagellata", "<b>Choanoflagellata</b>", x)
    return(x)
  }) +
  theme(axis.text.y = ggtext::element_markdown())
```
