---
title: "Potting Abundance"
author: "Gleison M. Azevedo"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  results = FALSE
)
```

```{r libs}
library(readr)
library(magrittr)
library(ggplot2)
library(hrbrthemes)
library(tinter)
```

```{r funcs}
# Custom tick function
tick_function <- function(x) {
  seq(x[2], 0, length.out = 3) %>% head(-1) %>% tail(-1) %>% { ceiling(./5)*5 }
}

# Função para calcular cumulativo e plotar com linha de 90%
plot_cumulative <- function(data, signature) {
  
  # Obter todas as categorias possíveis de clade_name
  all_clades <- node_annotation %>%
    arrange(desc(root)) %>%
    dplyr:: select(clade_name) %>%
    unique()
  
  # Filtrar e calcular cumulativo
  cumulative_data <- node_annotation %>%
    filter(Signature == signature) %>%
    arrange(desc(root)) %>%
    group_by(-root, clade_name) %>%
    summarise(count = n(), .groups = "drop") %>%
    mutate(cumulative_sum = cumsum(count)) %>%
    rename("root" = "-root")
  
  cumulative_data <- all_clades %>%
    left_join(cumulative_data)
  
  for (i in 2:nrow(cumulative_data)) {
    if (is.na(cumulative_data$cumulative_sum[i])) {
      cumulative_data$cumulative_sum[i] <- cumulative_data$cumulative_sum[i - 1]
    }
  }
  
  # Selecionar nomes do eixo x
  clade_name <- unique(all_clades$clade_name)
  
  # Calcular 90% do total
  total_genes <- sum(na.omit(cumulative_data$count))
  threshold_90 <- 0.9 * total_genes
  root_90 <- cumulative_data$clade_name[which(cumulative_data$cumulative_sum >= threshold_90)][1]
  cumulative_90 <- cumulative_data$cumulative_sum[which(cumulative_data$cumulative_sum >= threshold_90)][1]
  
  # Criar gráfico
  p <- ggplot(cumulative_data, aes(x = factor(clade_name, levels = clade_name), y = cumulative_sum)) +
    geom_bar(stat = "identity", 
             fill = annotation_colors[signature]) +
    geom_hline(yintercept = threshold_90, linetype = "dashed", color = "red") +
    labs(x = NULL, y = NULL, title = paste(signature)) +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  
  return(p)
}

plot_cumulative_2 <- function(data, signature) {
  
  # Obter todas as categorias possíveis de clade_name
  all_clades <- node_annotation %>%
    arrange(desc(root)) %>%
    dplyr:: select(clade_name) %>%
    unique()
  
  # Filtrar e calcular cumulativo
  cumulative_data <- node_annotation %>%
    filter(Signature == signature) %>%
    arrange(desc(root)) %>%
    group_by(-root, clade_name) %>%
    summarise(count = n(), .groups = "drop") %>%
    mutate(cumulative_sum = cumsum(count)) %>%
    rename("root" = "-root")
  
  cumulative_data <- all_clades %>%
    left_join(cumulative_data)
  
  for (i in 2:nrow(cumulative_data)) {
    if (is.na(cumulative_data$cumulative_sum[i])) {
      cumulative_data$cumulative_sum[i] <- cumulative_data$cumulative_sum[i - 1]
    }
  }
  
  # Selecionar nomes do eixo x
  clade_name <- unique(all_clades$clade_name)
  
  # Calcular 90% do total
  total_genes <- sum(na.omit(cumulative_data$count))
  threshold_90 <- 0.9 * total_genes
  root_90 <- cumulative_data$clade_name[which(cumulative_data$cumulative_sum >= threshold_90)][1]
  cumulative_90 <- cumulative_data$cumulative_sum[which(cumulative_data$cumulative_sum >= threshold_90)][1]
  
  # Criar gráfico
  p <- ggplot(cumulative_data, aes(x = factor(clade_name, levels = clade_name), y = cumulative_sum)) +
    geom_bar(stat = "identity", 
             fill = annotation_colors[signature]) +
    geom_hline(yintercept = threshold_90, linetype = "dashed", color = "red") +
    labs(x = NULL, y = NULL, title = paste(signature)) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.margin = margin(1, 1, 0, 1))
  
  return(p)
}

plot_cumulative_3 <- function(node_annotation) {
  
  all_clades <- node_annotation %>%
    arrange(desc(root)) %>%
    dplyr::select(clade_name) %>%
    unique()

  cumulative_data <- node_annotation %>%
    dplyr::select(-Signature) %>%
    unique() %>%
    arrange(desc(root)) %>%
    group_by(-root, clade_name) %>%
    summarise(count = n(), .groups = "drop") %>%
    mutate(cumulative_sum = cumsum(count)) %>%
    rename("root" = "-root") %>%
    right_join(all_clades, by = "clade_name") %>%
    fill(cumulative_sum, .direction = "down")

  return(cumulative_data)
}
```

```{r themes}
# Plotting colors and labels
annotation_colors <- c(
  "cell adhesion"                               = "#06141FFF"
  ,"extracellular matrix organization"          = "#742C14FF"
  ,"epithelial to mesenchymal transition"       = "#3D4F7DFF"
  ,"regulation of metallopeptidase activity"    = "#E48C2AFF"
  ,"cell junction organization"                  ="#72874EFF"
  ,"cellular extravasation"                      ="#046E8FFF"
)

annotation_labels <- c(
   "cell adhesion"                              = "Adesão celular"
  ,"extracellular matrix organization"          = "Organização da matriz \nextracelular" 
  ,"epithelial to mesenchymal transition"       = "Transição \nepitélio-mesênquimal"
  ,"regulation of metallopeptidase activity"    = "Regulação da atividade \nda metalopeptidase"
  ,"cell junction organization"                 = "Organização da \njunção celular"
  ,"cellular extravasation"                     = "Extravasão celular"
)

# This vertical line indicates the first metazoan (Amphimedon queenslandica / Ctenophora)
choanoflagellata_line <- geom_vline(
  xintercept = "Sphaeroforma arctica"
  ,color      = "#FF0000"
  ,linetype   = "11"
  ,alpha      = 1
  ,linewidth  = 0.25
)

# Plotting
theme_main <- theme(
  panel.spacing      = unit(2.5, "pt")
  ,strip.background   = element_blank()
  ,panel.grid.major.x = element_blank()
  ,panel.grid.major.y = element_line(linewidth = 0.25, linetype = "dotted", color = "#E0E0E0")
  ,strip.text.x       = element_text(size = 9, angle = 90, hjust = 0, vjust = 0.5, color = "#757575")
  ,strip.text.y       = element_text(size = 10, angle = 0, hjust = 0, vjust = 0.5, color = "#757575")
  ,axis.title         = element_text(size = 15, color = "#424242")
  ,axis.ticks.x       = element_blank()
  ,axis.text.x        = element_blank()
  ,axis.text.y        = element_text(size = 5.5)
  ,legend.position    = "none"
)

theme_supplementary <- theme(
  panel.grid.major.x = element_line(color = "#E0E0E0", linewidth = 0.25, linetype = "dotted")
  ,panel.grid.major.y = element_blank()
  ,strip.text.y       = element_text(size = 7, angle = 0, hjust = 0, vjust = 0.5, color = "#757575")
  ,strip.text.x       = element_text(size = 7, angle = 90, hjust = 0, vjust = 0.5, color = "#757575")
  ,axis.title         = element_text(size = 12, color = "#424242")
  ,axis.ticks         = element_line(colour = "grey20")
  ,axis.text.y        = element_text(size = 6, angle = 0, hjust = 1, vjust = 0.5, color = "#757575")
  ,axis.text.x        = element_text(size = 6)
)

theme_average <- theme(
  panel.spacing      = unit(1, "pt")
  ,axis.title         = element_text(color = "#424242")
  ,axis.text          = element_text(color = "#757575")
  ,axis.text.x        = element_text(size = 7, angle = -45, vjust = 0, hjust = 0)
  ,axis.text.y        = element_text(size = 5)
  ,strip.background   = element_blank()
  ,strip.text         = element_text(color = "#757575")
  ,strip.text.y       = element_text(angle = 0, hjust = 0, vjust = 0.5)
)

theme_big <- theme(
  panel.spacing      = unit(0.5, "pt")
  ,panel.grid.major.x = element_line(linewidth = 0.1, linetype = "dashed")
  ,panel.grid.major.y = element_blank()
  ,strip.background   = element_blank()
  ,strip.text.x       = element_text(size = 8, angle = 90, hjust = 0.5, vjust = 0)
  ,strip.text.y       = element_text(size = 8, angle = 0, hjust = 0, vjust = 0.5)
  ,axis.text.x        = element_text(size = 6, angle = 90, vjust = 0, hjust = 0)
  ,axis.text.y        = element_text(size = 4.5)
  ,axis.ticks         = element_line(size = 0.1)
)
```

## Load Data

```{r data}
map_ids <- vroom::vroom("../results/orthology_data/map_ids.csv")
groot_df <- vroom::vroom("../results/orthology_data/groot_df.csv")
nodelist <- vroom::vroom("../results/orthology_data/nodelist.csv ")
gene_cogs <- vroom::vroom("../results/orthology_data/gene_cogs.csv")
cogs <- vroom::vroom("../results/orthology_data/cogs.csv")
df <- vroom::vroom("../results/metastasis_genes/metastasis_genes.csv")
load("../results/orthology_data/genebridge_ogr.RData")
load("../assets/string_eukaryotes.rda")

## Naming the rooted clades and getting the final results table
CLADE_NAMES <- "https://raw.githubusercontent.com/dalmolingroup/neurotransmissionevolution/ctenophora_before_porifera/analysis/geneplast_clade_names.tsv"

lca_names <- read_table(CLADE_NAMES)

lca_names %<>% rename("lca" = root)
```



```{r run}
lca_spp <- ogr@spbranches %>%
  rename("taxid" = ssp_id, "species" = ssp_name, "lca" = "branch") %>%
  mutate(taxid_order = row_number()) %>%
  dplyr::select(lca, taxid, taxid_order)

clade_taxids <- lca_spp
clade_names <- lca_names

cog_annotation <- map_ids %>%
  left_join(groot_df, by = c("stringId" = "string_id")) %>%
  left_join(df, by = c("queryItem" = "external_gene_name")) %>%
  distinct(queryItem, cog_id, Signature) %>%
  dplyr::select(cog_id, Signature) %>%
  unique()

cog_abundance_by_taxid <- cogs %>%
  filter(cog_id %in% nodelist[["cog_id"]]) %>%
  count(taxid, cog_id, name = "abundance") %>%
  left_join(cog_annotation, by = "cog_id")

# Mapping species to clade info
ordered_species <- string_eukaryotes %>%
  dplyr::select(taxid, ncbi_name) %>%
  left_join(clade_taxids, by = "taxid") %>%
  left_join(clade_names, by = "lca") %>%
  na.omit() %>% unique() %>%
  mutate(
    ncbi_name  = fct_reorder(ncbi_name, -taxid_order)
    ,clade_name = fct_reorder(clade_name, -taxid_order)
  )

avg_abundance_by_function <- cog_abundance_by_taxid %>%
  group_by(taxid, Signature) %>%
  summarise(avg_abundance = mean(abundance)) %>%
  ungroup() %>%
  # Adding species and clade info
  left_join(ordered_species %>% mutate(taxid = as.double(taxid)), by = "taxid") %>%
  unique() %>%
  na.omit()

capped_abundance_by_function <- avg_abundance_by_function %>%
  # mutate(capped_abundance = ifelse(abundance >= 100, 100, abundance)) %>%
  group_by(Signature) %>%
  mutate(
    # max_abundance = max(abundance[lca <= 29])
    max_abundance = avg_abundance[lca <= 29] %>% { mean(.) + 3*sd(.) }
    ,abundance     = ifelse(avg_abundance >= max_abundance, pmin(max_abundance, 100), pmin(avg_abundance, 100)))
  
# Mapping roots and proteins info
node_annotation <- nodelist %>%
  inner_join(gene_cogs, by = c("node" = "string_id", "cog_id")) %>%
  inner_join(df, by = c("queryItem" = "external_gene_name")) %>%
  distinct(queryItem, cog_id, Signature, root, clade_name)

# List of signatures
signatures <- unique(node_annotation$Signature)

# Criar e salvar plots
plots <- lapply(signatures, function(s) plot_cumulative(node_annotation, s))
plots2 <- lapply(signatures, function(s) plot_cumulative_2(node_annotation, s))

roots_seq <- node_annotation %>%
  arrange(desc(root)) %>%
  dplyr:: select(root, clade_name) %>%
  unique()

roots_seq$clade_name <- factor(roots_seq$clade_name, levels = roots_seq$clade_name)
```



```{r plots}
cumulative_data <- plot_cumulative_3(node_annotation)

# Criar gráfico
ggplot(cumulative_data, aes(x = factor(clade_name, levels = clade_name), y = cumulative_sum)) +
  geom_bar(stat = "identity") +
  labs(x = NULL, y = NULL) +
  geom_text(aes(label=cumulative_sum), vjust = 2, size = 3, color = "white") +
  theme_modern_rc() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.margin = margin(1, 1, 0, 1))
```

```{r plots}
# Plotting by species
ggplot(avg_abundance_by_function) +
  # Geoms  ----------------
choanoflagellata_line +
  geom_bar(
    aes(x = ncbi_name, y = avg_abundance, fill = Signature, color = after_scale(darken(fill, 0.1)))
    ,stat = "identity"
  ) +
  # Labels  ---------------
 xlab("Espécies") +
  ylab("Abundância média de proteínas em grupos ortólogos") +
  #ylab("Average protein abundance in orthologous groups") +
  # Scales ----------------
scale_y_continuous(breaks = tick_function, minor_breaks = NULL) +
  scale_fill_manual(values = annotation_colors %>% darken(0.1)) +
  # Styling ---------------
facet_grid(
  Signature ~ clade_name
  ,scales   = "free"
  ,space    = "free"
  ,labeller = labeller(annotation = annotation_labels)
) +
  theme_classic() + 
  theme_main

# Plotting by species capped
ggplot(capped_abundance_by_function) +
  # Geoms  ----------------
choanoflagellata_line +
  geom_bar(
    aes(x = ncbi_name, y = abundance, fill = Signature, color = after_scale(darken(fill, 0.1)))
    ,stat = "identity"
  ) +
  # Labels  ---------------
  xlab("Espécies") +
  ylab("Abundância média de proteínas em grupos ortólogos") +
  #ylab("Average protein abundance in orthologous groups") +
  # Scales ----------------
  scale_y_continuous(breaks = tick_function, minor_breaks = NULL) +
  scale_fill_manual(values = annotation_colors %>% darken(0.1)) +
  # Styling ---------------
facet_grid(
  Signature ~ clade_name
  ,scales   = "free"
  ,space    = "free"
  ,labeller = labeller(annotation = annotation_labels)
) +
  theme_classic() + 
  theme_main
```

```{r plots}
# Ploting by clade
ggplot(avg_abundance_by_function) +
  geom_bar(
    aes(x = clade_name, y = avg_abundance, fill = Signature, color = after_scale(darken(fill, 0.1)))
    ,stat = "summary"
    ,fun  = "mean"
  ) +
  scale_y_continuous(breaks = tick_function, minor_breaks = NULL) +
  scale_fill_manual(values = annotation_colors, guide = "none") +
  facet_grid(
    Signature ~ .
    ,scales   = "free"
    ,space    = "free_y"
    ,labeller = labeller(annotation = sub("\n", "", annotation_labels))
  ) +
  xlab("Clados") +
  ylab("Abundância média por clado") +
  theme_classic() + 
  theme_average
```


```{r plots}
plots_combined <- c(plots[1:6], plots2[6])

combined_plot <- patchwork::wrap_plots(
  plots_combined,
  nrow = 8,
  ncol = 1
)

print(combined_plot)
```
```{r trash}
  # Obter todas as categorias possíveis de clade_name
  all_clades <- node_annotation %>%
    arrange(desc(root)) %>%
    dplyr::select(clade_name) %>%
    unique()


  # Calcular o cumulativo agrupando por Signature (processos biológicos)
  cumulative_genes <- nodelist %>%
    arrange(desc(root)) %>%
    dplyr::select("queryItem", 
                  "root",
                  "clade_name",
                  "cellular extravasation",
                  "cell junction organization",           
                  "cell adhesion",                          
                  "extracellular matrix organization",     
                  "epithelial to mesenchymal transition",  
                  "regulation of metallopeptidase activity") %>%
    group_by(-root, clade_name) %>%
    summarise(count_genes = n(), .groups = "drop") %>%
    mutate(cumulative_sum = cumsum(count_genes)) %>%
    right_join(all_clades, by = "clade_name") %>%
    fill(cumulative_sum, .direction = "down")
  
  
  # Calcular a soma cumulativa para cada processo biológico
cumulative_bp <- nodelist %>%
  # Selecionar as colunas necessárias
  dplyr::select("queryItem", 
                "root",
                "clade_name",
                "cellular extravasation",
                "cell junction organization",           
                "cell adhesion",                          
                "extracellular matrix organization",     
                "epithelial to mesenchymal transition",  
                "regulation of metallopeptidase activity") %>%
  # Remover duplicatas de genes para a mesma raiz (root)
  distinct(root, queryItem, .keep_all = TRUE) %>%
  # Certificar-se de que todas as colunas de processos biológicos são numéricas
  mutate(across(c("cellular extravasation",
                  "cell junction organization",
                  "cell adhesion",                          
                  "extracellular matrix organization",     
                  "epithelial to mesenchymal transition",  
                  "regulation of metallopeptidase activity"), 
                ~ as.numeric(.))) %>%
  # Agrupar por root e clade_name
  group_by(root, clade_name) %>%
  # Calcular a soma dos genes para cada processo biológico, removendo NAs
  summarise(across(c("cellular extravasation",
                     "cell junction organization",
                     "cell adhesion",                          
                     "extracellular matrix organization",     
                     "epithelial to mesenchymal transition",  
                     "regulation of metallopeptidase activity"), 
                   ~ sum(. , na.rm = TRUE)),
            .groups = "drop") %>%
  # Ordenar pela raiz para garantir a ordem de soma cumulativa
  arrange(desc(root)) %>%
  # Calcular a soma cumulativa para cada processo biológico
  mutate(across(c("cellular extravasation",
                  "cell junction organization",
                  "cell adhesion",                          
                  "extracellular matrix organization",     
                  "epithelial to mesenchymal transition",  
                  "regulation of metallopeptidase activity"),
                ~ cumsum(.))) %>%
  # Unir com todos os clados
  right_join(all_clades, by = "clade_name") %>%
  # Preencher valores faltantes (caso haja clados sem dados em algum root)
  fill(everything(), .direction = "down")
  
  
  cumulative_data <- left_join(cumulative_genes, cumulative_bp)
  

  
  cumulative_long <- cumulative_data %>%
  pivot_longer(cols = 6:11,
               names_to = "process",
               values_to = "count")

# Criar o gráfico de barras empilhadas
ggplot(cumulative_long, aes(x = factor(root), y = cumulative_sum, fill = process)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(x = "Root", y = "Cumulative Gene Count", fill = "Biological Process") +
 # geom_text(aes(label=count), vjust = 2, size = 3, color = "white") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() +
  coord_flip()  # Gira o gráfico para melhor visualização
 


long_data <- cumulative_data %>%
  pivot_longer(cols = 6:11, 
               names_to = "Process", 
               values_to = "Value")

# Criar o gráfico
ggplot() +
  # Gráfico de barras para cumulative_sum
  geom_bar(data = cumulative_data, 
           aes(x = factor(-root), y = cumulative_sum), 
           stat = "identity", fill = "lightblue") +
  
  # Gráfico de linhas para os processos biológicos
  geom_line(data = long_data, 
            aes(x = factor(-root), y = Value, color = Process, group = Process), 
            size = 1) +
  
  # Adicionar pontos para as linhas
  #geom_area(data = long_data, 
  #           aes(x = factor(-root), y = Value, color = Process, group = Process), 
  #           size = 2) +
  
  # Rótulos e tema
  labs(x = "Clade Name", y = "Values", 
       title = "Cumulative Sum and Biological Processes",
       fill = "Cumulative Sum",
       color = "Biological Processes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```
