---
title: "05_archetype_network"
author: "gleisonm"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  results = FALSE
)
```

```{r libs}
library(GeneBridge)
library(httr)
library(geneplast.data)
library(readr)
library(dplyr)
library(purrr)
library(biomaRt)
library(magrittr)
library(KEGGREST)
library(ape)
library(tidyverse)
library(data.table)
library(stringi)
library(AnnotationHub)
library(sourcetools)
library(here)
```

```{r funcs}
# Get STRING interactions
 get_network_interaction <- function(map_ids, stringId, species_id = "9606") {
 
   identifiers <- map_ids %>% pull(stringId) %>% na.omit %>% paste0(collapse="%0d") 
 
   req2 <- RCurl::postForm(
     "https://string-db.org/api/tsv/network",
     identifiers = identifiers, 
     required_core = "0", 
     species = species_id,
     .opts = list(ssl.verifypeer = FALSE)
   )
   
   int_network <- read.table(text = req2, sep = "\t", header = TRUE)
   
   int_network <- unique(int_network)
   
   return(int_network)
 }

get_network_partness_interaction <- function(map_ids, stringId, species_id = "9606") {
  # Extrai e formata os IDs de interesse
  identifiers <- map_ids %>% 
    pull({{stringId}}) %>% 
    na.omit() %>% 
    paste0(collapse = "%0d")
  
  # Envia a requisição para a API do STRING
  response <- POST(
    url = "https://string-db.org/api/tsv/interaction_partners?identifiers=",
    body = list(
      identifiers = identifiers,
      required_score = "0",
      species = species_id
    ),
    encode = "form",
    config = httr::config(ssl_verifypeer = FALSE)
  )
  
  # Converte o conteúdo da resposta em tabela
  int_network <- read.table(text = content(response, as = "text"), 
                            sep = "\t", 
                            header = TRUE)
  
  # Remove duplicatas
  int_network <- unique(int_network)
  
  return(int_network)
}

combine_scores <- function(dat, evidences = "all", confLevel = 0.4) {
  if(evidences[1] == "all"){
    edat<-dat[,-c(1,2,ncol(dat))]
  } else {
    if(!all(evidences%in%colnames(dat))){
      stop("NOTE: one or more 'evidences' not listed in 'dat' colnames!")
    }
    edat<-dat[,evidences]
  }
  if (any(edat > 1)) {
    edat <- edat/1000
  }
  edat<-1-edat
  sc<- apply(X = edat, MARGIN = 1, FUN = function(x) 1-prod(x))
  dat <- cbind(dat[,c(1,2)],combined_score = sc)
  idx <- dat$combined_score >= confLevel
  dat <-dat[idx,]
  return(dat)
}
```

```{r data}
nodelist <- vroom::vroom("../results/orthology_data/nodelist.csv ")
metamonada_nodelist <- subset(nodelist, nodelist$clade_name == "Metamonada")
```

```{r data}
# Metastasis Genes data frame
df <- vroom::vroom("../results/metastasis_genes/metastasis_genes.csv")

# NCBI Eukaryotes 
load('../assets/string_eukaryotes.rda')

## Table with Orthologous Groups and their proteins
#download_if_missing("https://stringdb-static.org/download/COG.mappings.v11.0.txt.gz")

cogs <- fread(
  "../assets/COG.mappings.v11.0.txt.gz",
  header           = F,
  stringsAsFactors = F,
  skip             = 1,
  sep              = "\t",
  col.names        = c("taxid.string_id","cog_id"),
  select           = c(1,4),
  quote            = ""
)

# Query Phylotree and OG data
ah <- AnnotationHub()
meta <- query(ah, "geneplast")
load(meta[["AH83116"]])
cogdata <- dplyr::select(cogdata, "protein_id", "ssp_id", "og_id" = "cog_id")
```

```{r metamonada_network}
metamonada_int <- get_network_partness_interaction(metamonada_nodelist, queryItem)

# Recomputing scores
metamonada_edgelist <- combine_scores(metamonada_int, 
                                  evidences = c("ascore", "escore", "dscore"), 
                                  confLevel = 0.4)

colnames(metamonada_edgelist) <- c("stringId_A", "stringId_B", "combined_score")

# Remove o species id
metamonada_edgelist$stringId_A <- substring(metamonada_edgelist$stringId_A, 6, 1000)
metamonada_edgelist$stringId_B <- substring(metamonada_edgelist$stringId_B, 6, 1000)

# Exporting for package use
#metamonada_edgelist |> 
  #vroom::vroom_write(file = here("results/orthology_data/metamonada_edgelist.csv"), delim = ",")
```

```{r run}
map_ids <- unique(c(metamonada_edgelist$stringId_A, metamonada_edgelist$stringId_B))

# Spliting first column into taxid and string_id
separated_ids <- cogs %$% stri_split_fixed(taxid.string_id, pattern = ".", n = 2, simplify = T)

cogs[["taxid"]]     <- separated_ids[, 1]
cogs[["string_id"]] <- separated_ids[, 2]

# Freeing up some memory
rm(separated_ids)

# keeping only eukaryotes
cogs %<>% dplyr::select(-taxid.string_id) %>% 
  filter(taxid %in% string_eukaryotes[["taxid"]])
gc()

cogdata2 <- cogs %>% 
  dplyr::select(protein_id = string_id, ssp_id = taxid, og_id = cog_id)
cogdata2 <- as.data.frame(cogdata2)

ogdata <- unique(rbind(cogdata, cogdata2))

# Subsetting cogs of interest - METASTASIS GENES
gene_cogs <- cogs %>%
  filter(string_id %in% map_ids) %>%
  dplyr::select(-taxid) %>%
  group_by(string_id) %>%
  summarise(n = n(), cog_id = paste(cog_id, collapse = " / "))

## Proteins with multiple COGs
gene_cogs %>% filter(n > 1)

# Resolving main proteins
gene_cogs_resolved <- tribble(
  ~string_id, ~cog_id,
"ENSP00000298910", "COG0515", #COG0515 / COG2114 / COG4886
"ENSP00000239462", "KOG1225",#KOG1225 / KOG2579
"ENSP00000261537", "KOG4582",
"ENSP00000262903", "COG0666", #COG0666 / COG5021
"ENSP00000285928", "COG0194", #COG0194 / COG4886
"ENSP00000288266", "KOG3536",
"ENSP00000288368", "KOG3519", #KOG3519 / KOG4428
"ENSP00000296792", "KOG0267", #KOG0267 / KOG0310
"ENSP00000298229", "KOG4384",
"ENSP00000304604", "COG0194", #COG0194 / COG5021
"ENSP00000305702", "KOG2723",
"ENSP00000310561", "KOG1449", #KOG1449 / KOG3564
"ENSP00000317272", "KOG3610",
"ENSP00000329219", "KOG1922", #KOG1922 / KOG1923
"ENSP00000331901", "KOG1627",
"ENSP00000335044", "KOG2312", #KOG2312 / KOG2744
"ENSP00000339299", "KOG0032", #KOG0032 / KOG4240
"ENSP00000355890", "COG0008", #COG0008 / COG0442
"ENSP00000356379", "KOG0165",
"ENSP00000359085", "KOG1836", #KOG1836 / KOG3512
"ENSP00000362115", "KOG4270",
"ENSP00000362824", "COG0457", #COG0457 / COG3914
"ENSP00000366953", "KOG0264", #KOG0264 / KOG4155
"ENSP00000370950", "KOG3656",
"ENSP00000376306", "KOG0976",
"ENSP00000394107", "KOG4734",
"ENSP00000418112", "COG3338", #COG3338 / COG5599
"ENSP00000418734", "COG1310", #COG1310 / COG5259
"ENSP00000430269","COG0596", #COG0596 / COG1011
"ENSP00000454786", "KOG0129",
"ENSP00000457991", "COG2114", #COG2114 / COG4886
"ENSP00000471457", "KOG1453"
)

# Removing unresolved cases and adding manual assignments
gene_cogs %<>%
  filter(n == 1) %>%
 dplyr:: select(-n) %>%
  bind_rows(gene_cogs_resolved)
```

## GeneBridge Rooting

```{r genebridge}
## Run GeneBridge
ogr <- newBridge(ogdata=ogdata, phyloTree=phyloTree, ogids = gene_cogs$cog_id, refsp="9606")

ogr <- runBridge(ogr, penalty = 2, threshold = 0.5, verbose = TRUE)

ogr <- runPermutation(ogr, nPermutations=1000, verbose=FALSE)

res <- getBridge(ogr, what="results")

```

## GeneBridge results processing

```{r run}
## Naming the rooted clades and getting the final results table
CLADE_NAMES <- "https://raw.githubusercontent.com/dalmolingroup/neurotransmissionevolution/ctenophora_before_porifera/analysis/geneplast_clade_names.tsv"

lca_names <- read_table(CLADE_NAMES)

groot_df <- res %>%
  tibble::rownames_to_column("cog_id") %>%
  dplyr::select(cog_id, root = Root) %>%
  inner_join(lca_names) %>%
  inner_join(gene_cogs) 

#groot_df |> 
  #vroom::vroom_write(file = here("results/orthology_data/groot_df.csv"), delim = ",")

## Create
nodelist <- data.frame(node = unique(c(metamonada_edgelist$stringId_A, metamonada_edgelist$stringId_B)))

merged_paths <- merge(nodelist, groot_df, by.x = "node", by.y = "string_id")
merged_paths <- subset(merged_paths, clade_name == "Metamonada")

```

## Network

```{r network}
net <- get_network_interaction(merged_paths, "node")
net <- combine_scores(net, evidences = c("ascore", "escore", "dscore"), confLevel = 0.4)

net <-  net %>%
  separate(stringId_A,
           into = c("ncbi_taxon_id", "stringId_A"),
           sep = "\\.") %>%
  separate(stringId_B,
           into = c("ncbi_taxon_id", "stringId_B"),
           sep = "\\.") 

network_filtered <- net %>%
  dplyr::select(stringId_A, stringId_B) |>
  distinct()

nodelist <-
  data.frame(node = unique(c(network_filtered$stringId_A, network_filtered$stringId_B))) %>%
  left_join(merged_paths, by = c("node" = "node"))

dict <- getBM(
  attributes = c("ensembl_peptide_id", "hgnc_symbol"),
  filters = "ensembl_peptide_id",
  values = nodelist$node,
  mart = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
)

nodelist <- merge(nodelist, dict, by.x = "node", by.y = "ensembl_peptide_id", all.x = TRUE)

nodelist <- nodelist %>%
  mutate(in_metamonada = if_else(node %in% metamonada_nodelist$node, TRUE, FALSE))

# Network Metrics
connected_nodes <- rle(sort(c(network_filtered[,1], network_filtered[,2])))
connected_nodes <- data.frame(count=connected_nodes$lengths, node=connected_nodes$values)
connected_nodes <- left_join(nodelist, connected_nodes, by = c("node" = "node"))
```

```{r onchoenrich}
library(oncoEnrichR)

oeDB <- oncoEnrichR::load_db(cache_dir = "../../.cache/")

myc_report <- oncoEnrichR::onco_enrich(query = out_metamonada$hgnc_symbol, oeDB = oeDB, project_title = "Metamonada Side Network")

oncoEnrichR::write(report = myc_report, oeDB = oeDB, file = "../../myc_report_oncoenrichr.html", format = "html")

```


```{r enrich}
library(clusterProfiler)

in_metamonada <- subset(nodelist, in_metamonada == TRUE)
out_metamonada <- subset(nodelist, in_metamonada == FALSE)


in_enrich <- enrichGO(
gene = in_metamonada$hgnc_symbol,
OrgDb = "org.Hs.eg.db",
ont = "BP",
pAdjustMethod = "BH",
keyType = 'SYMBOL'
)
df_go_in <- in_enrich@result
df_go_in <- df_go_in[df_go_in$qvalue <= 0.05,]

out_enrich <- enrichGO(
gene = out_metamonada$hgnc_symbol,
OrgDb = "org.Hs.eg.db",
ont = "BP",
pAdjustMethod = "BH",
keyType = 'SYMBOL'
)
df_go_out <- out_enrich@result
df_go_out <- df_go_out[df_go_out$qvalue <= 0.05,]


kegg_enrich <- enrichKEGG(
gene = in_metamonada$hgnc_symbol,
organism = "hsa",
keyType = "ncbi-geneid",
pAdjustMethod = "BH",
)
```



```{r graph}
library(RedeR)
library(dplyr)
library(igraph)

# Inicializar o RedeR
rdp <- RedPort()
calld(rdp)

# Criação do grafo completo usando `network_filtered`
g <- graph_from_data_frame(d=network_filtered, directed=FALSE)

# Adiciona os atributos de `nodelist` ao grafo
V(g)$name <- nodelist$node
V(g)$label <- nodelist$hgnc_symbol
V(g)$color <- nodelist$color

# Seleciona os nós com `in_metamonada` igual a TRUE
nodes_in_metamonada <- nodelist$node[nodelist$in_metamonada == TRUE]

# Extrai o subgrafo correspondente
g_metamonada <- induced_subgraph(g, vids=nodes_in_metamonada)

# Adiciona o grafo completo ao RedeR
N1 <- addGraphToRedeR(g, theme="tm1")

# Adiciona o subgrafo de `in_metamonada` como um grafo aninhado
N2 <- addGraphToRedeR(g_metamonada, isNested=TRUE, parent=N1, theme="tm2")

# Ajuste de layout
mergeOutEdges(Bnlevels=2)
relaxRedeR(p1=100, p2=100, p3=5, p4=150, p5=5, p8=10, p9=20)
```
